#NAME: Naim Ayat
#EMAIL: naimayat@ucla.edu
#ID: 000000000

.SILENT:

default:
	gcc -pthread -o lab1a -g lab1a.c -Wall -Wextra

clean:
	rm -f lab1a *.o *.txt  *.tar.gz

dist:
	tar -czvf lab1a-000000000.tar.gz lab1a.c Makefile README
