#NAME: Naim Ayat
#EMAIL: naimayat@ucla.edu
#ID: 000000000
default:
	# From Piazza thread 407
	echo 'python lab3b.py $$1' > lab3b
	chmod 700 lab3b

clean:
	rm -rf lab3b *.tar.gz

dist:
	tar -czf lab3b-000000000.tar.gz lab3b.py Makefile README